### ISSUE TITLE
Broken links tracker

### ISSUE THREAD

**Issue by jberkus** [kalkayan/k8s.elections#10]
Tracking issue for broken links.  Post them below.

**Comment by jberkus** [comment]
Link for "export CSV of ballots" is broken under admin.

**Comment by kalkayan** [comment]
Broken result link

<img width="1002" alt="Screenshot 2021-01-06 at 8 44 52 AM" src="https://user-images.githubusercontent.com/73003119/103724916-7861e800-4ffb-11eb-95fd-4de4632f74cb.png">

**Comment by jberkus** [comment]
closing this in favor of https://github.com/elekto-io/elekto/issues/2
