### ISSUE TITLE
Create exception request form

### ISSUE THREAD

**Issue by jberkus** [kalkayan/k8s.elections#3]
Here is the layout of the exception request form.  It will require some additional metadata, particularly we'll need a date that exceptions end, as well as another markdown description block, this time of the exception process.

Title: Voter Exception form for {election_name}

Due Date: This exception form closes on {date_exceptions_end}

Description: {exception_details}

Fields for submitter, all but comments are required:

Name: {short text}

Email: {short text}

Chat ID: {short text}

Description of Your Contributions: {long text}

Other Comments: {long text}

**Comment by jberkus** [comment]
Hmmm, now that I think about it, I don't think we need a full markdown block for the exception process.  Just long description text would be enough.

**Comment by kalkayan** [comment]
Updated `election.yaml`, added exception info. Is this okay? @jberkus 

<img width="1002" alt="Screenshot 2021-01-03 at 1 43 09 AM" src="https://user-images.githubusercontent.com/73003119/103465799-0c665200-4d65-11eb-8cb5-6d1ffd952d1b.png">

**Comment by jberkus** [comment]
+1, do it.
