### ISSUE TITLE
Text spacing in app and accessibility

### ISSUE THREAD

**Issue by jberkus** [kalkayan/k8s.elections#9]
Currently the application screen is designed with a large amount of fixed whitespace, which looks fairly good when the text is at its default small size.  However, voters with small screened devices, or voters who enlarge text for readability, find themselves scrolling forever down very narrow lines of a few words of text.

Clearly some kind of relative spacing that works better for resizing is called for.  Not a high priority, but filing this issue so that we don't lose track of it.

**Comment by jberkus** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/115146/103583889-69612580-4e95-11eb-9f36-2f1f1d0ce3f8.png)

**Comment by kalkayan** [comment]
@jberkus can you check the spacing on [https://test.elekto.io/app/elections](https://test.elekto.io/app/elections)? and close if it is fixed.

**Comment by jberkus** [comment]
This is fixed.  Thanks!
